description = "thin-edge.io default recipes"
dependencies = [
    "core/persist-root-home",
    "rugpi-extra/zsh",

    "essentials",
    "persist-network-manager",
    "set-wifi",
    "mosquitto",
    "sbom",
    "ssh",
]